[tool.poetry]
name = "cve-bob"
version = "0.1.0"
description = "Slack Bot for NVD CVE API"
authors = ["Noland Seigler <57370691+nolandseigler@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
slackclient = "^2.9.2"
slackeventsapi = "^2.2.1"
Flask = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
